In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [2]:
ds=pd.read_csv("kxzyPW7cQfiJDe9mAwBl_SMSSpam-1564990592100.csv")

In [3]:
ds.head()

ham  \
0   ham   
1  spam   
2   ham   
3   ham   
4  spam   

  Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
0                      Ok lar... Joking wif u oni...                                                               
1  Free entry in 2 a wkly comp to win FA Cup fina...                                                               
2  U dun say so early hor... U c already then say...                                                               
3  Nah I don't think he goes to usf, he lives aro...                                                               
4  FreeMsg Hey there darling it's been 3 week's n...

In [4]:
ds.shape

(5573, 2)

In [6]:
len(ds)

5573

In [11]:
x=ds.iloc[:,1].values
y=ds.iloc[:,0].values
x
y

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [12]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [13]:
le=LabelEncoder()
le.fit(y)
new_le=le.transform(y)
new_le

array([0, 1, 0, ..., 0, 0, 0])

In [15]:
tf=TfidfVectorizer(stop_words="english")
tf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [19]:
xtf=tf.fit_transform(x)
x=xtf.toarray()
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
x[0]
print(tf.inverse_transform(x[0]))
len(x[0])

[array(['joking', 'lar', 'ok', 'oni', 'wif'], dtype='<U34')]


8442

In [22]:
mnb=MultinomialNB()
x_train,x_test,y_train,y_test=train_test_split(x,new_le,test_size=.33,random_state=42)

In [27]:
mnb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

mnb.score(x_train,y_train)

In [28]:
mnb.score(x_train,y_train)

0.9780337530136619

In [30]:
pred=mnb.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
actual=np.array(y_test)
actual

array([0, 0, 0, ..., 0, 0, 0])